name: Issue to Text File

on:
  issues:
    types: [opened]

jobs:
  create_text_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create text file
        run: |
          echo -e "Issue Title: ${{ github.event.issue.title }}\nIssue Body: ${{ github.event.issue.body }}" > issue-${{ github.event.issue.number }}.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add issue-${{ github.event.issue.number }}.txt
          git commit -m "Add issue #${{ github.event.issue.number }} details"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
