on:
    issues:
        types: [opened]

jobs:
    js-action:
        runs-on: ubuntu-latest
        name: try js action
        steps:
          - name: require js action
            id: test
            uses: Danryg/insecure_custom_action_test@v1.3
            with:
                file-input: "XAXAXAXAX"
          - name: output
            run: echo "the output is ${{steps.test.outputs}}"
